version: '3'

services:
    teachteam-mysql-db:
        image: mysql:5.7
        container_name: curso-mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: root
            MYSQL_ROOT_HOST: '%'